import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const appDir = path.resolve(scriptDir, "..");
const projectRoot = path.resolve(appDir, "..", "..");
const matrixPath = path.join(
  projectRoot,
  "hierarchical clustering",
  "clustering trees from DB",
  "emd_swd_ir_distance_matrix.csv",
);
const namesPath = path.join(
  projectRoot,
  "hierarchical clustering",
  "region_acronym2name.json",
);

const matrixText = await fs.readFile(matrixPath, "utf8");
const acronymNames = JSON.parse(await fs.readFile(namesPath, "utf8"));
const regionLabels = matrixText.split(/\r?\n/, 1)[0].split(",").slice(1);

function expandRegionName(label) {
  if (acronymNames[label]) return acronymNames[label];
  const expanded = label
    .split(/\s+/)
    .map((token) => acronymNames[token] || token)
    .filter((value, index, all) => all.indexOf(value) === index);
  return expanded.join(" + ");
}

function classifyRegion(label, name) {
  const text = `${label} ${name}`.toLowerCase();
  if (/cbl|cbv|cbdn|cerebell/.test(text)) return "Cerebellum";
  if (/ca[1-4]|dgc|dgr|dgu|sub\b|hippoc|dentate/.test(text)) return "Hippocampal formation";
  if (/hth|hypothalam/.test(text)) return "Hypothalamus";
  if (/thalam|\bcm\b|\bmd\b|\blp\b|\blg\b|\bmg\b|\bva\b|\bvl|\bvpl\b|\bpul\b|\bpf\b|\bre\b/.test(text)) {
    return "Thalamus";
  }
  if (/gpe|gpi|nac|putamen|\bpu\b|claustr|\bcla\b|bnst|\bsi\b|\bsth\b|basal/.test(text)) {
    return "Basal ganglia";
  }
  if (/amyg|\bbl\b|\bbm\b|\bcen\b|\bcoa\b|\bla\b|sept|\bsep\b|olfact|aon|piriform|\bpir\b/.test(text)) {
    return "Limbic / olfactory";
  }
  if (/pag|pons|pont|\bpn\b|pnan|pnen|pnrf|medulla|midbrain|tect|superior collic|inferior collic|\bsc\b|\bic\b|red nucleus|\brn\b|substantia nigra|\bsn\b|raphe|\bdr\b|tegment|motor nucleus|brainstem|moan|morf|moen|mosr|\bio\b|\bpb\b|\bmn\b|\bdtg\b/.test(text)) {
    return "Brainstem";
  }
  if (/cortex|cortical|\ba\d+|\bm1c\b|\bs1c\b|\bv1c\b|\bv2\b|ofc|rsc|psc|spc|stc|mtc|vfc|pphc|ptr|prostriata|\bpro\b|\btf\b|entorhinal|\blec\b|\bmec\b|insula|\bfi\b|\bitc\b|\bidg\b|\big\b/.test(text)) {
    return "Cerebral cortex";
  }
  return "Other subcortical";
}

const cellTypes = [
  "Excitatory neuron",
  "Inhibitory neuron",
  "Astrocyte",
  "Oligodendrocyte",
  "OPC",
  "Microglia",
  "Endothelial",
];

const profileByGroup = {
  "Cerebral cortex": [0.43, 0.17, 0.13, 0.13, 0.05, 0.06, 0.03],
  "Hippocampal formation": [0.49, 0.11, 0.13, 0.12, 0.05, 0.07, 0.03],
  Thalamus: [0.31, 0.19, 0.14, 0.19, 0.06, 0.08, 0.03],
  Hypothalamus: [0.25, 0.25, 0.16, 0.16, 0.06, 0.09, 0.03],
  "Basal ganglia": [0.27, 0.27, 0.13, 0.17, 0.06, 0.07, 0.03],
  "Limbic / olfactory": [0.38, 0.21, 0.13, 0.13, 0.05, 0.07, 0.03],
  Cerebellum: [0.48, 0.16, 0.10, 0.13, 0.04, 0.06, 0.03],
  Brainstem: [0.24, 0.22, 0.15, 0.22, 0.06, 0.08, 0.03],
  "Other subcortical": [0.30, 0.21, 0.15, 0.18, 0.06, 0.07, 0.03],
};

function hashUnit(text) {
  let hash = 2166136261;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0) / 4294967295;
}

function makeComposition(label, group) {
  const base = profileByGroup[group] || profileByGroup["Other subcortical"];
  const perturbed = base.map((value, index) => {
    const jitter = (hashUnit(`${label}:${index}`) - 0.5) * 0.06;
    return Math.max(0.012, value + jitter);
  });
  const total = perturbed.reduce((sum, value) => sum + value, 0);
  return Object.fromEntries(
    cellTypes.map((cellType, index) => [
      cellType,
      Number((perturbed[index] / total).toFixed(5)),
    ]),
  );
}

const regions = regionLabels.map((label, index) => {
  const name = expandRegionName(label);
  const group = classifyRegion(label, name);
  return {
    id: `DBR-${String(index + 1).padStart(3, "0")}`,
    acronym: label,
    name,
    group,
    layoutIndex: index,
    composition: makeComposition(label, group),
  };
});

const dataModule = `// Generated by scripts/build_region_catalogue.mjs.\n` +
  `// Region identities are repository-derived; composition values are illustrative.\n` +
  `window.DIGITALBRAIN_REGION_DATA = ${JSON.stringify({
    metadata: {
      regionUniverse: "DigitalBrain Table 2 hierarchy",
      regionCount: regions.length,
      atlasRegionContext: 165,
      compositionProvenance: "illustrative",
      coordinateProvenance: "schematic",
      generatedFrom: [
        "hierarchical clustering/clustering trees from DB/emd_swd_ir_distance_matrix.csv",
        "hierarchical clustering/region_acronym2name.json",
      ],
    },
    cellTypes,
    regions,
  }, null, 2)};\n`;

const csvRows = ["region,cell_type,proportion"];
for (const region of regions) {
  for (const cellType of cellTypes) {
    csvRows.push(
      `${JSON.stringify(region.acronym)},${JSON.stringify(cellType)},${region.composition[cellType]}`,
    );
  }
}

await fs.mkdir(path.join(appDir, "data"), { recursive: true });
await fs.writeFile(path.join(appDir, "data", "regions.js"), dataModule);
await fs.writeFile(
  path.join(appDir, "data", "demo_cell_composition.csv"),
  `${csvRows.join("\n")}\n`,
);

console.log(`Generated ${regions.length} regions and ${csvRows.length - 1} composition rows.`);
