import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { classifyRegionGroup } from "./region_groups.mjs";
import { CELL_TYPES, makeComposition } from "./region_composition.mjs";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const appDir = path.resolve(scriptDir, "..");
const webRoot = path.resolve(appDir, "..");
const projectRoot = path.resolve(appDir, "..", "..");
const matrixPath = path.join(
  projectRoot,
  "hierarchical clustering",
  "clustering trees from DB",
  "emd_swd_ir_distance_matrix.csv",
);
const namesPath = path.join(
  projectRoot,
  "hierarchical clustering",
  "region_acronym2name.json",
);
const hierarchyPath = path.join(
  webRoot,
  "data",
  "vendor",
  "region_hierarchy_paths.json",
);

const matrixText = await fs.readFile(matrixPath, "utf8");
const acronymNames = JSON.parse(await fs.readFile(namesPath, "utf8"));
const { paths: hierarchyPaths } = JSON.parse(
  await fs.readFile(hierarchyPath, "utf8"),
);
const regionLabels = matrixText.split(/\r?\n/, 1)[0].split(",").slice(1);

function expandRegionName(label) {
  if (acronymNames[label]) return acronymNames[label];
  const expanded = label
    .split(/\s+/)
    .map((token) => acronymNames[token] || token)
    .filter((value, index, all) => all.indexOf(value) === index);
  return expanded.join(" + ");
}

const cellTypes = [...CELL_TYPES];

const regions = regionLabels.map((label, index) => {
  const name = expandRegionName(label);
  const group = classifyRegionGroup(label, hierarchyPaths);
  return {
    id: `DBR-${String(index + 1).padStart(3, "0")}`,
    acronym: label,
    name,
    group,
    layoutIndex: index,
    composition: makeComposition(label, group),
  };
});

const dataModule = `// Generated by scripts/build_region_catalogue.mjs.\n` +
  `// Groups are derived from the vendored region hierarchy by scripts/region_groups.mjs;\n` +
  `// run scripts/sync_region_groups.mjs --check to verify they still agree.\n` +
  `// Region identities are repository-derived; composition values are illustrative.\n` +
  `window.DIGITALBRAIN_REGION_DATA = ${JSON.stringify({
    metadata: {
      regionUniverse: "DigitalBrain Table 2 hierarchy",
      regionCount: regions.length,
      atlasRegionContext: 165,
      compositionProvenance: "illustrative",
      coordinateProvenance: "schematic",
      generatedFrom: [
        "hierarchical clustering/clustering trees from DB/emd_swd_ir_distance_matrix.csv",
        "hierarchical clustering/region_acronym2name.json",
        "data/vendor/region_hierarchy_paths.json",
      ],
    },
    cellTypes,
    regions,
  }, null, 2)};\n`;

const csvRows = ["region,cell_type,proportion"];
for (const region of regions) {
  for (const cellType of cellTypes) {
    csvRows.push(
      `${JSON.stringify(region.acronym)},${JSON.stringify(cellType)},${region.composition[cellType]}`,
    );
  }
}

await fs.mkdir(path.join(appDir, "data"), { recursive: true });
await fs.writeFile(path.join(appDir, "data", "regions.js"), dataModule);
await fs.writeFile(
  path.join(appDir, "data", "demo_cell_composition.csv"),
  `${csvRows.join("\n")}\n`,
);

console.log(`Generated ${regions.length} regions and ${csvRows.length - 1} composition rows.`);
