// 用层级树校正 data/regions.js 的 region.group（并连带重算示意构成），
// 再把同一份分组同步进 data/connectivity.js 的节点。
//
//   node scripts/sync_region_groups.mjs --check    只报告偏差，有偏差则退出码 1
//   node scripts/sync_region_groups.mjs            就地改写
//
// 为什么不直接重跑 build_region_catalogue.mjs：它的两个输入
// （hierarchical clustering/ 下的距离矩阵与命名表）在当前工作副本里已不存在，
// 而 regions.js 里的 acronym / name / layoutIndex 都已核对无误，
// 只有 group 需要修，所以就地校正比整表重建更小、更可核。

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { classifyRegionGroup, REGION_GROUPS } from "./region_groups.mjs";
import { CELL_TYPES, makeComposition } from "./region_composition.mjs";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const appDir = path.resolve(scriptDir, "..");
const webRoot = path.resolve(appDir, "..");
const hierarchyPath = path.join(webRoot, "data", "vendor", "region_hierarchy_paths.json");
const regionsPath = path.join(appDir, "data", "regions.js");
const compositionCsvPath = path.join(appDir, "data", "demo_cell_composition.csv");
const connectivityPath = path.join(appDir, "data", "connectivity.js");

const checkOnly = process.argv.includes("--check");

// regions.js / connectivity.js 都是 `window.X = {...}` 形式的数据模块；
// 用一个空 window 求值即可取出对象，不需要解析 JS 语法。
async function loadDataModule(file, globalName) {
  const code = await fs.readFile(file, "utf8");
  const window = {};
  new Function("window", code)(window);
  const value = window[globalName];
  if (!value) throw new Error(`${file} did not define window.${globalName}`);
  return { code, value };
}

const { paths } = JSON.parse(await fs.readFile(hierarchyPath, "utf8"));
const { value: regionData } = await loadDataModule(regionsPath, "DIGITALBRAIN_REGION_DATA");

const drift = [];
const corrected = regionData.regions.map((region) => {
  const group = classifyRegionGroup(region.acronym, paths);
  if (group !== region.group) drift.push({ ...region, group });
  return { ...region, group, composition: makeComposition(region.acronym, group) };
});

const stray = [...new Set(corrected.map((region) => region.group))].filter(
  (group) => !REGION_GROUPS.includes(group),
);
if (stray.length) {
  throw new Error(`Hierarchy produced groups outside the UI vocabulary: ${stray.join(", ")}`);
}

if (checkOnly) {
  for (const region of drift) {
    const before = regionData.regions.find((item) => item.acronym === region.acronym).group;
    console.error(`DRIFT ${region.acronym}: ${before} -> ${region.group}  (${region.name})`);
  }
  if (drift.length) {
    console.error(`${drift.length} region group(s) disagree with the hierarchy.`);
    process.exit(1);
  }
  console.log(`OK ${corrected.length} region groups agree with the hierarchy.`);
  process.exit(0);
}

// —— 改写 regions.js ——
// 排版与 build_region_catalogue.mjs 一致，未变的区域因此逐字节不变。
const dataModule =
  `// Generated by scripts/build_region_catalogue.mjs.\n` +
  `// Groups are derived from the vendored region hierarchy by scripts/region_groups.mjs;\n` +
  `// run scripts/sync_region_groups.mjs --check to verify they still agree.\n` +
  `// Region identities are repository-derived; composition values are illustrative.\n` +
  `window.DIGITALBRAIN_REGION_DATA = ${JSON.stringify(
    {
      metadata: {
        ...regionData.metadata,
        generatedFrom: [
          "hierarchical clustering/clustering trees from DB/emd_swd_ir_distance_matrix.csv",
          "hierarchical clustering/region_acronym2name.json",
          "data/vendor/region_hierarchy_paths.json",
        ],
      },
      cellTypes: [...CELL_TYPES],
      regions: corrected,
    },
    null,
    2,
  )};\n`;
await fs.writeFile(regionsPath, dataModule);

// —— 改写 demo_cell_composition.csv ——
const csvRows = ["region,cell_type,proportion"];
for (const region of corrected) {
  for (const cellType of CELL_TYPES) {
    csvRows.push(
      `${JSON.stringify(region.acronym)},${JSON.stringify(cellType)},${region.composition[cellType]}`,
    );
  }
}
await fs.writeFile(compositionCsvPath, `${csvRows.join("\n")}\n`);

// —— 同步 connectivity.js ——
// 该文件由 Python 以 separators=(",",":") 压缩成单行，整体重序列化会有
// 1485 条边的浮点排版风险，所以只对受影响节点做锚定到 acronym 的定点替换。
let connectivityCode = await fs.readFile(connectivityPath, "utf8");
const { value: connectivityData } = await loadDataModule(
  connectivityPath,
  "DIGITALBRAIN_CONNECTIVITY_DATA",
);
const groupByAcronym = new Map(corrected.map((region) => [region.acronym, region.group]));
let patchedNodes = 0;
for (const node of connectivityData.nodes) {
  const group = groupByAcronym.get(node.acronym);
  if (!group) throw new Error(`connectivity.js node ${node.acronym} is not in regions.js`);
  if (group === node.group) continue;
  const anchor = `"acronym":${JSON.stringify(node.acronym)},"name":${JSON.stringify(node.name)},"group":`;
  const occurrences = connectivityCode.split(anchor).length - 1;
  if (occurrences !== 1) {
    throw new Error(`Expected exactly one record for ${node.acronym}, found ${occurrences}`);
  }
  connectivityCode = connectivityCode.replace(
    `${anchor}${JSON.stringify(node.group)}`,
    `${anchor}${JSON.stringify(group)}`,
  );
  patchedNodes += 1;
}
if (patchedNodes) await fs.writeFile(connectivityPath, connectivityCode);

for (const region of drift) console.log(`FIXED ${region.acronym} -> ${region.group}`);
console.log(
  `Rewrote ${corrected.length} regions (${drift.length} group change(s)) and patched ${patchedNodes} connectivity node(s).`,
);
